"""first creation of gemuese table

Revision ID: 2762e06369f9
Revises: 
Create Date: 2021-12-17 13:02:12.870756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2762e06369f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemuese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=255), nullable=True),
    sa.Column('cultivator', sa.String(length=255), nullable=True),
    sa.Column('laenge', sa.Float(), nullable=True),
    sa.Column('preis', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gemuese')
    # ### end Alembic commands ###
